# Generated by Django 4.2.6 on 2023-12-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dentist',
        ),
        migrations.AddField(
            model_name='dentist',
            name='age',
            field=models.IntegerField(help_text='eg.  248-293-2984', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
