# Generated by Django 4.2.6 on 2023-12-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_patient_dentist_dentist_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='age',
            field=models.IntegerField(help_text='eg.  248-293-2984', max_length=100, null=True),
        ),
    ]
